package vn.com.frankle.karaokelover.database.entities;

import android.support.annotation.NonNull;

import com.pushtorefresh.storio.sqlite.annotations.StorIOSQLiteColumn;
import com.pushtorefresh.storio.sqlite.annotations.StorIOSQLiteType;

import vn.com.frankle.karaokelover.database.tables.ArtistTable;

/**
 * Created by duclm on 7/24/2016.
 */

// This annotation will trigger annotation processor
// Which will generate type mapping code in compile time,
// You just need to link it in your code.
@StorIOSQLiteType(table = ArtistTable.TABLE)
public class DAOArtist {
    /**
     * If object was not inserted into db, id will be null
     */
    @StorIOSQLiteColumn(name = ArtistTable.COLUMN_ID, key = true)
    int id;

    @StorIOSQLiteColumn(name = ArtistTable.COLUMN_NAME)
    String name;

    @StorIOSQLiteColumn(name = ArtistTable.COLUMN_ISVIETNAMESE)
    int is_vietnamese;

    // leave default constructor for AutoGenerated code!
    DAOArtist() {
    }

    private DAOArtist(int id, @NonNull String name, int is_vietnamese) {
        this.id = id;
        this.name = name;
        this.is_vietnamese = is_vietnamese;
    }

    @NonNull
    public static DAOArtist newArtist(int id, @NonNull String name, int is_vietnamese) {
        return new DAOArtist(id, name, is_vietnamese);
    }

    public int getId() {
        return id;
    }

    @NonNull
    public String getName() {
        return name;
    }

    public int isVietnamese() {
        return is_vietnamese;
    }

}
