package vn.com.frankle.karaokelover.database.entities;

import android.support.annotation.NonNull;

import com.pushtorefresh.storio.sqlite.annotations.StorIOSQLiteColumn;
import com.pushtorefresh.storio.sqlite.annotations.StorIOSQLiteType;

import vn.com.frankle.karaokelover.database.tables.KaraokeTable;

/**
 * Created by duclm on 7/24/2016.
 */

// This annotation will trigger annotation processor
// Which will generate type mapping code in compile time,
// You just need to link it in your code.
@StorIOSQLiteType(table = KaraokeTable.TABLE)
public class DAOKaraoke {
    /**
     * If object was not inserted into db, id will be null
     */
    @StorIOSQLiteColumn(name = KaraokeTable.COLUMN_ID, key = true)
    int id;

    @StorIOSQLiteColumn(name = KaraokeTable.COLUMN_ARTIST)
    int artist;

    @StorIOSQLiteColumn(name = KaraokeTable.COLUMN_VIDEOID)
    String video_id;

    // leave default constructor for AutoGenerated code!
    DAOKaraoke() {
    }

    private DAOKaraoke(int id, int artist, @NonNull String video_id) {
        this.id = id;
        this.artist = artist;
        this.video_id = video_id;
    }

    @NonNull
    public static DAOKaraoke newArtist(int id, int artist, @NonNull String video_id) {
        return new DAOKaraoke(id, artist, video_id);
    }

    @NonNull
    public String getVideoID() {
        return this.video_id;
    }

    public int getArtistID(){
        return artist;
    }

    public String toString(){
        return video_id;
    }
}
