package vn.com.frankle.karaokelover.database.entities

import com.pushtorefresh.storio.sqlite.annotations.StorIOSQLiteColumn
import com.pushtorefresh.storio.sqlite.annotations.StorIOSQLiteType

import vn.com.frankle.karaokelover.database.tables.FavoriteTable


/**
 * Created by duclm on 14-Nov-16.
 */
@StorIOSQLiteType(table = FavoriteTable.TABLE)
class Favorite {
    /**
     * If object was not inserted into db, id will be null
     */
    @StorIOSQLiteColumn(name = FavoriteTable.COLUMN_ID, key = true)
    internal var id: Long? = null

    @StorIOSQLiteColumn(name = FavoriteTable.COLUMN_VIDEO_ID)
    lateinit internal var video_id: String

    @StorIOSQLiteColumn(name = FavoriteTable.COLUMN_COLLECTION_ID)
    internal var collection_id: Int? = null

    // leave default constructor for AutoGenerated code!
    internal constructor() {
    }

    private constructor(id: Long?, video_id: String, collection_id: Int) {
        this.id = id
        this.video_id = video_id
        this.collection_id = collection_id
    }

    fun id(): Long? {
        return id
    }

    fun videoId(): String {
        return video_id
    }

    fun collectionId(): Int {
        return collection_id!!
    }

    companion object {

        fun newFavorite(id: Long?, video_id: String, collection_id: Int): Favorite {
            return Favorite(id, video_id, collection_id)
        }

        fun newFavorite(video_id: String, collection_id: Int): Favorite {
            return Favorite(null, video_id, collection_id)
        }
    }
}
